### ISSUE TITLE
Extension methods configuration

### ISSUE THREAD

**Issue by benjaminsampica** [soenneker/soenneker.utils.autobogus#108]
I might be missing that this is already built-in, but it would be super awesome to be able to build configuration via `With(e => e.Name)`, `.Without`, etc.. I understand it's slower, but subclassing overrides per-class kind of stinks - especially when I could have many different overrides for the same class, I feel like it's harder to grok.  Thoughts?

**Comment by soenneker** [comment]
Can you expand on your example some? Was this supported in AutoBogus before?

I removed a bunch of extension methods from the autofakerconfigbuilder but I think the majority of it exists within the AutoFakerConfig... 

I could definitely be wrong.

Happy to help solve any friction!

**Comment by benjaminsampica** [comment]
Looking to do something like this (from AutoBogus). 

 ‘’’
// Configure an AutoFaker<T> 
var personFaker = new AutoFaker<Person>()
  .RuleFor(fake => fake.Id, fake => fake.Random.Int())
  .Generate();
‘’’

**Comment by soenneker** [comment]
@benjaminsampica Fair points. I'm not opposed to a Bogus wrapper. I'll take a look.

**Comment by conradakunga** [comment]
@soenneker huge thanks for thanking this over and fixing some of the bugs (like `DateOnly `issues).

Cosign on @benjaminsampica - it would be great to allow customization the way AutoBogus classic did

**Comment by soenneker** [comment]
@benjaminsampica @conradakunga OK I've implemented `AutoFaker<T>`. I have some tests in place, but if you run into any issues with it please let me know. Thanks

**Comment by marcio-af-oliveira** [comment]
@soenneker I'm trying to use the new implemented `AutoFaker<T>` with a statis value for a property but it is throwing: **Object reference not set to an instance of an object.**

My implementation:

```
var test = new AutoFaker<Entity>()
    .RuleFor(e => e.TypeA, nameof(EnumTypeA.Lorem))
    .RuleFor(e => e.TypeB, nameof(EnumTypeB.Lorem))
    .Generate(3);
```

**Comment by soenneker** [comment]
@marcio-af-oliveira can you send me the full exception message with the callstack? I just built several tests just like how you have your code there and have no issues.
