### ISSUE TITLE
Is there a way to always create an empty list instead of null

### ISSUE THREAD

**Issue by rizi** [soenneker/soenneker.utils.autobogus#142]
The current default behaviour is that lists within an object are always null if the property is e.g IReadonlyCollection, is there a way that AutoFaker always creates an empty list instead of null?

Is there a way to configure this, without creating a custom binder?

I would also like to create a FakeItEasy fake if the property of an object is an abstract or interface type?

Note:
With the original AutoFaker this was quite easy because the method of the class AutoFakerBinder: "CreateInstance<TType>(AutoFakerContext..)" was declared as virtual.

Br

**Comment by soenneker** [comment]
Hi @rizi 

> The current default behaviour is that lists within an object are always null if the property is e.g IReadonlyCollection, is there a way that AutoFaker always creates an empty list instead of null?

If you're saying that a `IReadOnlyCollection` within a class are resulting in `null` after generation, that should not be the case. I created a test that verifying that. I'd be happy to look at any examples you have showing this.

> I would also like to create a FakeItEasy fake if the property of an object is an abstract or interface type?

None of those integrations have been built yet (Moq, FakeItEasy, etc)

> With the original AutoFaker this was quite easy because the method of the class AutoFakerBinder: "CreateInstance(AutoFakerContext..)" was declared as virtual.

Can you show me simple usage of this?

**Comment by rizi** [comment]
> Hi @rizi
> 
> > The current default behaviour is that lists within an object are always null if the property is e.g IReadonlyCollection, is there a way that AutoFaker always creates an empty list instead of null?
> 
> If you're saying that a `IReadOnlyCollection` within a class is resulting in `null` after generation, that should not be the case. I created a test verifying that they should be populated. I'd be happy to look at any examples you have showing this.
> 
> > I would also like to create a FakeItEasy fake if the property of an object is an abstract or interface type?
> 
> None of those integrations have been built yet (Moq, FakeItEasy, etc)
> 
> > With the original AutoFaker this was quite easy because the method of the class AutoFakerBinder: "CreateInstance(AutoFakerContext..)" was declared as virtual.
> 
> Can you show me simple usage of this?

Thx for the fast response:

@If you're saying that a IReadOnlyCollection within a class is resulting in null after generation, that should not be the case. I created a test verifying that they should be populated. I'd be happy to look at any examples you have showing this

I will double check it but yes I'm quite sure it's null, I mean if I create an instance of AutoFaker of some class with a property of IReadonlyCollection this property is null when I don't use .RuleFor --> I will prepare a sample.

@Can you show me simple usage of this?
That's how it was done with the old AutoFaker, just derive from AutoFakerBinder, override "CreateInstance(....)" and create a fake (FakeItEasy) if it's an interface or abstract class.
https://github.com/nickdodd79/AutoBogus/blob/master/src/AutoBogus.FakeItEasy/FakeItEasyBinder.cs

So you can just use A.CallTo(() =>....) to setup the fake, this can be quiet handy.

**Comment by soenneker** [comment]
> I will double check it but yes I'm quite sure it's null, I mean if I create an instance of AutoFaker of some class with a property of IReadonlyCollection this property is null when I don't use .RuleFor --> I will prepare a sample.

I created a commit testing for this (https://github.com/soenneker/soenneker.utils.autobogus/commit/6f659df6553d1a28a11c1852b50fa42d3a3a3972) so yes let me know if there's another way to replicate.

> That's how it was done with the old AutoFaker, just derive from AutoFakerBinder, override "CreateInstance(....)" and create a fake (FakeItEasy) if it's an interface or abstract class.

Oh, you're referring to the integrations. Yeah that stuff just isn't done yet.. perhaps will get to it soon

**Comment by rizi** [comment]
> > I will double check it but yes I'm quite sure it's null, I mean if I create an instance of AutoFaker of some class with a property of IReadonlyCollection this property is null when I don't use .RuleFor --> I will prepare a sample.
> 
> I created a commit testing for this ([6f659df](https://github.com/soenneker/soenneker.utils.autobogus/commit/6f659df6553d1a28a11c1852b50fa42d3a3a3972)) so yes let me know if there's another way to replicate.
> 
_So it seems I did something wrong, I try to figure it out._

> > That's how it was done with the old AutoFaker, just derive from AutoFakerBinder, override "CreateInstance(....)" and create a fake (FakeItEasy) if it's an interface or abstract class.
> 
> Oh, you're referring to the integrations. Yeah that stuff just isn't done yet.. perhaps will get to it soon

Would you mind if I send you a PR that makes the method virtual, so I can do it on my own, I think it would be quite helpful as an extension point.

Br

**Comment by rizi** [comment]
> @rizi Thanks for the tests. I've pushed an update that should fix this.
> 
> > I also have an additional question, is there a way to also support internal properties?
> 
> Yep, could you create a new issue for that?
> 
> > Would you mind if I send you a PR that makes the methods virtual (AutoFakeBinder -->
> 
> > public TType? CreateInstance(AutoFakerContext context, CachedType cachedType) and
> 
> > void PopulateInstance(object instance, AutoFakerContext context, CachedType cachedType), so I can do it on my own, I think it would be quite helpful as an extension point.
> 
> It is a bit more complicated than just making them virtual. I'll put some priority on this.

Thank you very much!

For the internal stuff I will open a new issue.

Br

**Comment by soenneker** [comment]
@rizi I created a new issue to track the abstract/interface types, closing this one.
