### ISSUE TITLE
Please add a way to support internal properties/fields

### ISSUE THREAD

**Issue by rizi** [soenneker/soenneker.utils.autobogus#143]
At the moment internal fields/properties are "ignored", it would be great to give the user of your library the possibility to tell AutoBogus that internal properties/fields should be taken into account as well.

Maybe some kind of global switch (e.g BindingFlags) to enable it if needed.

Br

**Comment by soenneker** [comment]
@rizi internal field/property is now supported - give it a try, let me know if you see any issues

**Comment by rizi** [comment]
@soenneker thx for the fix, it's wokring fine 👍.

br
