### ISSUE TITLE
Generate multiple creates nullable entries

### ISSUE THREAD

**Issue by unsafePtr** [soenneker/soenneker.utils.autobogus#158]
When trying to generate multiple entities it's generating nullable entries. Seems it's not a drop-in replacement for AutoBogus. I am using  NUnit as testing engine with parallel execution enabled.

![Screenshot 2024-05-08 172610](https://github.com/soenneker/soenneker.utils.autobogus/assets/22746240/65013b28-8de5-4b41-a0c9-48324671c4ca)

**Comment by soenneker** [comment]
Can you provide a simple example showing this issue? There are tests covering this scenario.

**Comment by unsafePtr** [comment]
I can share the exact code, but for example below example will throw NRE, while with AutoBogus it will work without any problem.

[TestProject2.zip](https://github.com/soenneker/soenneker.utils.autobogus/files/15263097/TestProject2.zip)

**Comment by soenneker** [comment]
@unsafePtr Thanks for providing the example. Please test with the latest version, and let me know.
