### ISSUE TITLE
'event' type properties cause an exception of "The type System.Void* may not be used as a type argument

### ISSUE THREAD

**Issue by mpickers** [soenneker/soenneker.utils.autobogus#258]
When you attempt to generate a fake of a class type that has an event type property, AutoFaker throws an exception.

Sample to reproduce the issue:

```
using Soenneker.Utils.AutoBogus;
using Soenneker.Utils.AutoBogus.Config;
using System.ComponentModel;
using System.Diagnostics;

namespace AutoBogusBug
{
   public class MyClass
   {
      public event PropertyChangedEventHandler PropertyChanged;    // <----- This property causes the issue
      public string FirstName { get; set; } = string.Empty;
   }

   internal class Program
   {
      static void Main(string[] args)
      {
         var optionalConfig = new AutoFakerConfig();
         var autoFaker = new AutoFaker(optionalConfig);
         var f = autoFaker.Generate<MyClass>();

         Debug.WriteLine(f.FirstName);
      }
   }
}
```

![image](https://github.com/user-attachments/assets/afe069da-0ccc-4c3a-a9b6-371e08245f8b)

**Comment by soenneker** [comment]
Thanks for the sample, will check it out soon

**Comment by soenneker** [comment]
@mpickers could you give the latest version a try? I made a few changes to exclude field and property delegates. Thanks

**Comment by mpickers** [comment]
@soenneker yes, works as expected now. 
Thanks for the prompt fix and your time creating this project...very helpful!
