### ISSUE TITLE
Non-generic AutoFaker is missing UseSeed and UseDateTimeReference

### ISSUE THREAD

**Issue by 304NotModified** [soenneker/soenneker.utils.autobogus#301]
Hi,

I like to use the `AutoFaker` to generate an object without knowing the type compile-time.

I need this for some snapshot tests. But I seems that `AutoFaker` is missing the `UseSeed` and `UseDateTimeReference` methods? Those methods are available on `AutoFakerT<>`

**Comment by 304NotModified** [comment]
Ah I found the underlying code as work around

```c#
var autoFaker = new AutoFaker();
autoFaker.Faker.DateTimeReference = FixedDate; // Instead of UseDateTimeReference(FixedData) 
autoFaker.Faker.Random = new Randomizer(seed); // Instead of UseSeed(seed)
```

**Comment by soenneker** [comment]
I'm going to close this as it seems like a decent enough way to achieve this... if you think it should belong on the AutoFaker object itself, let me know.

Thanks

**Comment by 304NotModified** [comment]
Shouldn't have the generic and non-generic AutoFaker has the same API design?

**Comment by soenneker** [comment]
Ah right because of the inheritance from Bogus. OK agreed

**Comment by soenneker** [comment]
UseSeed and UseDateTimeReference now exist on AutoFaker, thanks
