### ISSUE TITLE
AutoFaker<T> not respecting custom RuleFor for protected properties linked to public properties

### ISSUE THREAD

**Issue by Ephaltes** [soenneker/soenneker.utils.autobogus#341]
Hello,

I am encountering an issue where AutoFaker<T> does not work as expected when dealing with a protected property that is linked to a public property.

### Actual behaviour:
`AutoFaker<T>.RuleFor(data => data.MyList, new List())`

The List still gets initialized with 1 item, despite the rule specifying an empty list.

### Expected behaviour:
`AutoFaker<T>.RuleFor(data => data.MyList, new List())`

The List should be initialized as empty.

### Use Case:

I have a IReadOnlyCollection<T> exposed as a public property, and I need to modify the underlying list internally. To achieve this, I use a protected ICollection<T> for internal access:

`public IReadOnlyCollection<T> PublicList { get; private set; }
protected ICollection<T> InternalList => (ICollection<T>)PublicList;
`

The purpose of having this InternalList is to pass it to another module (e.g., a Mapper) that modifies the list. However, since the Mapper is in a different assembly, the internal access modifier cannot be used. Additionally, casting the IReadOnlyCollection<T> to ICollection<T> within the Mapper throws an error.

When I attempt to initialize the list with specific items using RuleFor, the behavior is not as expected. Even after applying a rule to initialize the list with 4 items, the list ends up with 5 items: the 4 I specified, plus 1 additional item generated by AutoBogus.

Please refer to the sample project and screenshot for further details.
![2024-10-15 19_08_38-Window](https://github.com/user-attachments/assets/02f66938-63f9-46d3-8a86-749a5367cc23)
[AutobogusTest.zip](https://github.com/user-attachments/files/17382334/AutobogusTest.zip)

**Comment by soenneker** [comment]
@Ephaltes What's happening is the protected member is being set via AutoFaker it's setting the public collection. So even though you're setting that rule, the public collection follows the rule, but then the protected member gets set and changes it again.

You could set a `RecursiveDepth` to 0 so it doesn't generate members automatically.. or you could change the `ReflectionCacheOptions` flags so it ignores protected members.. another other option is you could use an `AutoFakerGeneratorOverride`.
