### ISSUE TITLE
`AutoFakerOverrides` mentioned in the docs is not a class in this solution

### ISSUE THREAD

**Issue by baynezy** [soenneker/soenneker.utils.autobogus#65]
In the [docs](https://github.com/soenneker/soenneker.utils.autobogus/blob/main/README.md?plain=1#L66) you mention `AutoFakerOverrides`  which as far as I can tell is not a class in this project.

```csharp
autoFaker.Config.Overrides = new AutoFakerOverrides();
autoFaker.Config.Overrides.Add(new OrderOverride());
```

Am I missing something?

**Comment by soenneker** [comment]
Sorry about that - it should be:

```csharp
autoFaker.Config.Overrides = new List<AutoFakerGeneratorOverride>();
```

I've corrected it on the readme.
